### ISSUE TITLE
BT Audio Fix plugin doesn't enable

### ISSUE THREAD

**Issue by ContinualDissapointment** [redstonekasi/vendetta-plugins#5]
Seems on both IOS and Android the BT Handsfree Audio Fix plugin doesn't work on Vendetta.
Whether BT is connected, not, on, off, whether in call or not the toggle "flicks" but doesn't actually activate.

EED5355, 201.0, iPADOS 17.2
EED5355, 210.10, Android 13
Thanks

**Comment by Badbird5907** [comment]
Same issue on galaxy s21 on 206.16

**Comment by redstonekasi** [comment]
This issue has been fixed, please wait for the update to be review by proxy staff.

**Comment by ContinualDissapointment** [comment]
Unsure if this warrants a new ticket but on
Android 13 / Vendetta eed5355 / Discord 214.16 (214016)
The plugin now works perfectly, however on 
IpadOS 17.3 / Vendetta eed5355 / Discord 214.0 (54498)
the plugin still has the same behavior as before with the toggle not fully engaging.
On ipad Discord version 214.0 is the latest from the app-store (app last updated 6 days ago)
